### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by Profpatsch**
Improves formatting & documents every symbol in the module. Depends on #16 (because otherwise a merge conflict is introduced).

### CODE REVIEW

**Comment by Profpatsch** [comment]
I’d like to add some sections to the module, but it looks like the docs generator doesn’t support those at the moment?

**Comment by kritzcreek** [comment]
Thanks for the docs, unfortunately the formatting changes cause all kinds of conflicts on the compiler/0.12 branch. Do you think you could rebase your work against that branch and remove the formatting changes (The signatures got a lot shorter with the effect rows disappearing, and we don't do the double newline between declarations anywhere else)

**Comment by kritzcreek** [comment]
My plan is basically to add these changes to #20 and then use that to cut a new release :)

**Comment by Profpatsch** [comment]
@kRITZCREEK Done!

**Comment by kritzcreek** [comment]
Awesome, Thank you very much!

**Pull request merged**
